routes:
  - name: view#index
    url: /
    verb: GET

  - name: view#timezoneIndex
    url: /js/timezones.json
    verb: GET

  - name: view#setView
    url: /setView/{view}
    verb: GET

resources:
    backend:
        url: /backends
    calendars:
        url: /calendars
    events:
        url: /calendars/{calendarId}/events
    todos:
        url: /calendars/{calendarId}/todos
    journals:
        url: /calendars/{calendarId}/journals
    objects:
        url: /calendars/{calendarId}/objects